# Generated by Django 4.1 on 2022-09-02 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=250)),
                ('model_number', models.CharField(max_length=250)),
                ('serial_number', models.CharField(max_length=250)),
                ('registration_date', models.DateField()),
                ('warranty', models.BooleanField()),
                ('warranty_expiry', models.DateField(null=True)),
                ('personal_device', models.BooleanField()),
                ('location', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
