# Generated by Django 4.1 on 2022-09-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0002_alter_asset_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='personal_device',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='warranty',
            field=models.BooleanField(null=True),
        ),
    ]
